### ISSUE TITLE
[RFE] Add ability to re-order tokens

### ISSUE THREAD

**Issue by frozencemetery** [freeotp/freeotp-android#106]
Currently, the tokens seem to show in the order they were added, which means that adding a new token will show up at the top and displace all other tokens.  Slightly nicer would be if the new token showed up at the bottom (to avoid confusing muscle memory), but ideally there would be some way to move them around.

Thanks!

**Comment by robbix1206** [comment]
This is already in the android app !

**Comment by frozencemetery** [comment]
(I'm being informed this is already present.  Closing.)
