### ISSUE TITLE
Update app icon

### ISSUE THREAD

**Issue by mueller-ma** [freeotp/freeotp-android#110]
The github project has a really nice [icon](https://avatars0.githubusercontent.com/u/22221993?v=4&s=2000). What about using this as app icon?

**Comment by luzgabriel** [comment]
I agree, it is much better than the current icon (blue box)

**Comment by npmccallum** [comment]
For record keeping, the new icon is here: https://github.com/gnome-design-team/gnome-icons/blob/master/android/freeOTP.svg

**Comment by rdebeasi** [comment]
Any plans to release a new version of the application that includes this icon?

Thanks for building FreeOTP - I use it every day, and it's a fantastic tool!

**Comment by PanderMusubi** [comment]
Please, double check the proposed app icon to the guidelines of Material Design and fix where needed.

**Comment by siavashs** [comment]
Is the new icon [adaptive](https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html)?
