### ISSUE TITLE
Cannot login, whatever the service

### ISSUE THREAD

**Issue by andy-b-84** [freeotp/freeotp-android#111]
I paired the FreeOTP app on my phone to my professional AWS account and many personal accounts.
I cannot log in to any of these services.
I didn't list them all here as that would be a security issue for these, and am quite distressed as most of my accounts use this MFA feature.

**Comment by FSMaxB** [comment]
Does your phone have the correct time and date set?

**Comment by andy-b-84** [comment]
Good shot.

It didn't this morning, can't figure out why, I had to set it by hand, but I only set the hour.
I tried after having set the correct time, to no avail.
Then after reading your answer, the minutes were off by 1 , apparently that was enough to loose the system.

Thanks for your answer, now I have to find why my phone's clock got out of track :)

**Comment by FSMaxB** [comment]
One minute is enough, because most tokens change every 30 seconds. (the actual time is part of the QR-Code that you scan, but 30 seconds is the default).

**Comment by andy-b-84** [comment]
Just for the sake of others : I checked the option "internet time" off , which, of course, ment my phone didn't syncrhonise over NTP...

Sorry for the trouble, and again thank you for your help :)
