### ISSUE TITLE
Update ScanActivity.java to use Camera2 API

### ISSUE THREAD

**Issue by joekir** [freeotp/freeotp-android#112]
The Camera API is now deprecated and should be updated to the newer hardware API:
https://developer.android.com/reference/android/hardware/camera2/package-summary.html

**Comment by SilleBille** [comment]
The current app's minsdk is **14**. The new Camera API (**Camera2**) was added in **API level 21** and requires **minsdk version to be 21+**. If we update it, we will be _losing support for a whole lot of mobiles_ running pre lollipop versions in the market. 

**Reference**: https://stackoverflow.com/a/28417458/1853912

**Comment by joekir** [comment]
Fair point, there are 2 ways I can think of to accommodate the change :  
- Runtime check  :(
- Build-flavours  :(

I guess we could see what that looks like on a feature spike, but maintaining 2 sets of code might not be a great tradeoff for this Camera2 update.

**Comment by npmccallum** [comment]
This is no problem for me. Our next release will require 23+. People on old platforms can upgrade their Android or their devices. We aren't going to support old devices for ever.

Note that this plan depends on old FreeOTP being still installable on old devices.

**Comment by SilleBille** [comment]
@joekir I was thinking of the runtime check for 2 sets of code. But, if @npmccallum is fine, we can remove support for devices running API level 23 or lower. That way we still have only 1 set of code to maintain.

**Comment by npmccallum** [comment]
Fixed in c0dcf1c.
