### ISSUE TITLE
Modernize UI

### ISSUE THREAD

**Issue by joekir** [freeotp/freeotp-android#122]
Update User Interface to Android material design.

**Comment by luzgabriel** [comment]
What about making it look more like the Authenticator app looks? Minimalistic. Also, I think it's better to show all the codes at once instead of having to click at the one you want to see.

**Comment by joekir** [comment]
@luzgabriel Agree on minimalist and modern as that is mostly an objective decision. The click to view choice to me sounds more subjective and it may be worth gaining user feedback from the community on whether people like/dislike that feature. 

@npmccallum any comments/opinions on future UI?

**Comment by luzgabriel** [comment]
@joekir I really like the feature that copies the code when you click it though. I was working on a version of freotp with a Autherticator-like user interface last year, I will see if I find it and work on it again!

**Comment by nlgranger** [comment]
Having only one code shown at a time is IMO much better. If you type a bit slowly, you can quickly check if it has updated without reading through the different lines.

**Comment by dsommers** [comment]
To show all codes or "click-to-show" could be a user preference setting.
