### ISSUE TITLE
Store secrets in android keystore 

### ISSUE THREAD

**Issue by joekir** [freeotp/freeotp-android#123]
Leverage the [android keystore APIs](https://developer.android.com/training/articles/keystore.html) to store secrets instead of private shared preferences. 

This change should include migration support for current users.

**Comment by bufferoverflow** [comment]
This is the technique to solve #6

**Comment by joekir** [comment]
@npmccallum FYI I started working on this feature [See this branch for details](https://github.com/joekir/freeotp-android-veerless/commit/a496b05c53e7162881944294e0f95e68edcd898f) 

TODO:
- replace the inline hmac usage in Token.java with calls to the KeyStore wrapper
- create migration code to move secrets in SharedPrefs to the KeyStore
- Add [KeyGuardManager](https://developer.android.com/reference/android/app/KeyguardManager.html) checks to calling activities.
- Figure out what ProtectionParameter to use with KeyEntries in the store

It is also somewhat difficult to test as the android KeyStore cannot be mocked. I'm currently testing using a Java Symmetric KeyStore as the interface is the same, however we may want to look at moving to Android Studio 3 as it [provides runtime tests to facilitate this](https://developer.android.com/training/testing/junit-runner.html#ato-studio).
