### ISSUE TITLE
Able to take a screenshot of barcode scan screen.

### ISSUE THREAD

**Issue by applebaum** [freeotp/freeotp-android#124]
Wanted to let you guys know that while taking screenshots of main app page (with OTP) is disabled (without root overriding), one can still take a screenshot while scanning the QR.
[Example](https://localmonero.co/static/guide/12.png)

**Comment by joekir** [comment]
Good Catch! 

It does appear that that view is lacking the [FLAG_SECURE](https://developer.android.com/reference/android/view/Display.html#FLAG_SECURE). 

Are you wanting to contribute a PR fix for this, or just highlighting the issue?

**Comment by applebaum** [comment]
Yeah, I'd have contributed a PR, but I see you didn't wait for me.
