### ISSUE TITLE
Suggestion for future proofing - Steam Guard

### ISSUE THREAD

**Issue by Keaft** [freeotp/freeotp-android#136]
So lemme preface this by saying that I really don't know the inner workings of 2 Factor Authentication.
However, I do know is that getting a 5 alphanumeric character code is possible, which is what steam uses. See:
https://github.com/winauth/winauth

I'm not having much luck finding an android app that does both alphanumeric and up to 8 digits. I would love to make the switch from Authy and Steam Guard to just Freeotp.

To find your steam secret from your android device install and setup steam guard and edit: /data/data/com.valvesoftware.android.steam.community/files/SteamGuard-InsertCharactersHere

**Comment by rdebeasi** [comment]
It looks like a member of the dev team has [committed code that adds Steam Guard compatibility](https://github.com/freeotp/freeotp-android/commit/6ace9ccb3c2dd0fe13e97bc5773ff930a91bbb01). I'm not sure what the release schedule looks like, but this feature should be available when the next release occurs.

**Comment by rcpao** [comment]
How do we add a Steam entry manually (without a QR code to scan)?  How do we enter issuerExt="Steam"?  I tried "Steam" (without the quotes) in both jdoe@example.com and 18c5... fields, filled in Secret, while leaving the rest at defaults.  I still ended up with non-Steam 6 digit code results.

**Comment by JamesTheAwesomeDude** [comment]
I'm also experiencing this issue on `FreeOTP Version 1.5 (17)`, installed from the Play Store on Andoid 10.

No matter how I try to add Steam as a TOTP provider, I end up with the same, numeric, 6-digit code.

I'm using [ValvePython/steam](https://github.com/ValvePython/steam) to get the shared secrets.

As it stands, it looks like Steam support is broken in this app. This would be a tremendous feature; I wish it worked.

**Comment by JamesTheAwesomeDude** [comment]
Going over the code, I can't see any problem except — *how* is `IssuerExt` supposed to be set? Can we override it? I think if there were a mechanism to set that properly, it'd work.

**Comment by JamesTheAwesomeDude** [comment]
Disregard my previous 2 comments in favor of #250

@rcpao, take a look at that issue

**Comment by JamesTheAwesomeDude** [comment]
Also — should this issue be closed by #150?
