### ISSUE TITLE
Not allowing 0 as an interval

### ISSUE THREAD

**Issue by einsteinsfool** [freeotp/freeotp-android#145]
When you add an entry manually you can choose 0 as an interval. It shouldn't be allowed.
Also, when an entry with interval=0 is created and you click that entry, the app gets minimized.

I know there are more important things to change/add. Couldn't resist reporting, though.

**Comment by npmccallum** [comment]
This testing is very valuable. However, we are replacing the manual add screen with the online qr code generator: https://freeotp.github.io/qrcode.html
