### ISSUE TITLE
How i can install on android 2.3.6

### ISSUE THREAD

**Issue by RusGamer** [freeotp/freeotp-android#148]
Hello. I used google auth and today its just crashing! I read somewhere if i will use freeotp i can access to my google codes. But on Google Play only for 4.0+ android version (

**Comment by npmccallum** [comment]
Your Android version is no longer supported and does not receive security updates. It is horribly insecure. We will not support it either.

**Comment by RusGamer** [comment]
can you give me old version link with 2.3.6 andoid support. i need to recover google auth codes. There my wallets!

**Comment by npmccallum** [comment]
FreeOTP does not read codes from Google Authenticator. We can't help you. Sorry!
