### ISSUE TITLE
QR does not scan with Samsung GT-S7390 (Android 4.1.2)

### ISSUE THREAD

**Issue by somenxavier** [freeotp/freeotp-android#151]
When I go to scan QR code, nothing is scanned.

**Comment by somenxavier** [comment]
Related to https://github.com/freeotp/freeotp-android/issues/42

**Comment by bufferoverflow** [comment]
4.1.2 is unsupported according to https://en.wikipedia.org/wiki/Android_version_history , master branch is bound to API level 14 and upcoming features require API level 23. I recommend to update the device to latest version or use e.g. https://lineageos.org/ if Samsung is unable to provide updates.

**Comment by joekir** [comment]
@somenxavier can you post here (with sensitive content redacted) the format of the QR code when scanning with something like [Google's ZXing app](https://zxing.org)? I think that would help people better identify the problem.

**Comment by somenxavier** [comment]
@joekir The QR code is explained in [posteo page](https://posteo.de/en/help/what-is-two-factor-authentication-and-how-do-i-set-it-up). I hope it helps! What type of QR code is that?

**Comment by somenxavier** [comment]
@bufferoverflow I don't think so. The upgrade is impossible in my case. Perhaps postmarketOS could help me in distance future ;-)

**Comment by joekir** [comment]
Ticket is closed now, but just to be sure it wasn't an issue with posteo I tried this example from their site:

https://posteo.de/system/help_images/765/original/6-two-factor-authentification-enter-one-time-password.jpg

Which parses to this:
```
otpauth://totp/Posteo.de:john.example@posteo.de?issuer=Posteo.de&secret=ad4hy46wsc3sh4dt
```

This should be non-problematic (and works with the latest version of the app), some of our test cases have an identical format:

https://github.com/freeotp/freeotp-android/blob/e1e37420f5d87359959351f85387d0e9353c133c/app/src/test/java/org/fedorahosted/freeotp/TokenCodeTest.java#L18
