### ISSUE TITLE
Clicking edit on a token with custom icon sets to default before save

### ISSUE THREAD

**Issue by joekir** [freeotp/freeotp-android#155]
Steps to reproduce:

1. Create a token with a custom image
2. Click edit on that token
3. Notice that the token has already cleared your previous custom image before you have selected save

**Comment by max-wittig** [comment]
Fixed in https://github.com/freeotp/freeotp-android/commit/78b3803925298482c8b77498d6a5a32fae9aaee8

**Comment by joekir** [comment]
verified.
