### ISSUE TITLE
question: how to migrate data?

### ISSUE THREAD

**Issue by juanjgit** [freeotp/freeotp-android#168]
Hi

If I change my device, how do I migrate all the data related to accounts in freeotp?

**Comment by nicorikken** [comment]
I have successfully transferred my keys between phones using [this description](https://lists.fedorahosted.org/archives/list/freeotp-devel@lists.fedorahosted.org/message/5XCPBQT2QVK4PSOIHDH4AL3ZYCYB2JJV/):

Connect your phone and run:
```bash
adb backup -f freeotp.bak org.fedorahosted.freeotp
```

That will store the FreeOTP data to the file `freeotp.bak`.

To restore this data, just run:
```bash
adb restore freeotp.bak
```

**Comment by npmccallum** [comment]
We will not support backups.
