### ISSUE TITLE
Development

### ISSUE THREAD

**Issue by amilopowers** [freeotp/freeotp-android#170]
Hello

Is this app still under development?

F-Droid says that it has "a known vulnerability". And I am wondering what that might be.

Thanks for that amazing app!

**Comment by amilopowers** [comment]
Age below gives more info but I am a regular user and don't really know what that means.

https://f-droid.org/wiki/page/AntiFeature:KnownVuln

**Comment by 2SI3NX** [comment]
Yea other people would also like to know about this? if its updated here why isnt it pushed to F-droid then?

**Comment by smichel17** [comment]
The most recent version on f-droid is 1.5, updated 706 days ago. I see there have been many commits since then, so a new release would be nice.

**Comment by ben-8409** [comment]
I realize F-Droid is probably the preferred way to get this app, but an update on Google Play would be appreciated, too.

**Comment by mario-d-s** [comment]
@npmccallum Please let us know this project isn't dead 🙏

I don't know who's in charge of the FreeOTP org but seeing 0 people (not even yourself) is worrying.
Do you intend to pass the torch?

**Comment by max-wittig** [comment]
I think [andOTP](https://github.com/andOTP/andOTP) is the best alternative with many features, including keystore encryption, backups etc.
**Also it is updated and maintained.**

**Comment by ohaessler** [comment]
Thanks for creating freeotp. It's a great application.
As the question was not answered by now, I would like to know if freeotp is still maintained, or if this is no longer the case.
Also, when will a new version with the commit from July 6th be released?

Thanks
Oliver

**Comment by dpal** [comment]
The project is still alive.

Dmitri

**Comment by max-wittig** [comment]
@adambkaplan Wouldn't it make more sense to contribute missing features to https://github.com/andOTP/andOTP. FreeOTP is so far behind.
