### ISSUE TITLE
The github source compare to app in google store

### ISSUE THREAD

**Issue by afattahi54** [freeotp/freeotp-android#179]
I downloaded the app from google app store and also install it from git hub. 

There seems to be some differences the app in app store has more features. Would you mind to update the git hub too :)

Thanks

**Comment by npmccallum** [comment]
The app store version is actually old compared to git. We plan to release git soon. The code in git contains more features *except* for manual token addition which was removed.

**Comment by afattahi54** [comment]
Thanks... I was comparing the UI and found that the "manual token addition" was removed :) Is the code still in git hub

**Comment by npmccallum** [comment]
Yes, see https://github.com/freeotp/freeotp-android/commit/7851b8e4742b47063376ac5f01543b0d1fc0d42c. We do not intend to restore this functionality.
