### ISSUE TITLE
The code on GitHub is newer than what is avalible to Google Play and F-Droid

### ISSUE THREAD

**Issue by ShapeShifter499** [freeotp/freeotp-android#183]
The code on GitHub seems to have been updated in December 2017 but the builds on Google Play and F-Droid are a year old. Why is this?  Will these ever be updated?

**Comment by JeanFred** [comment]
See #179 :)

**Comment by ShapeShifter499** [comment]
Oops sorry, didn't see that. Feel free to close this issue then
