### ISSUE TITLE
REQUEST: Reveal code without copying to clipboard?

### ISSUE THREAD

**Issue by Fycbicbeth** [freeotp/freeotp-android#185]
Is it possible to add a setting that allows you to reveal a code without copying it to clipboard? When logging into multiple things it can clutter up my clipboard.

**Comment by dmdufrene** [comment]
I agree with @Fycbicbeth , this should be a thing.

**Ways to implement:**
- _Tap and hold_ to copy to clipboard.  _Regular Tap_ would just reveal code without copying.
- Dedicated _button to copy_ to clipboard.
- _Per account settings_ to copy to clipboard, or not.
- _Universal app setting_ to copy, or not.

I usually use my authenticator to input into a workstation, or other computer.  So  **adding to my clipboard is, at best, an unneeded annoyance, but could even be a _security risk_** (Albeit, a small chance of attack).

_Emphasis added to highlight key points.  No tone implied._

**Comment by basicmaster** [comment]
I agree with the above users.

Note that this issue is related to/a duplicate of #49, #58 and #63, where a patch already has been posted.

**Comment by MikeDawg** [comment]
Can I be the anti, to what everyone is putting here. I like it when the app automatically copies to the clipboard.

My only reason, is that long-clicking (I know now), and even clicking on the share button, take up some "potential" valuable time, when switching between apps and so on.

**Comment by basicmaster** [comment]
Well, a setting to enable/disable the clipboard copy behaviour is the thing requested by everyone, which should already address your needs ;-)

**Comment by AsciiWolf** [comment]
Any update regarding this issue? It is still not possible to turn off the clipboard copying on a latest FreeOTP version from Google Play.
