### ISSUE TITLE
Two TOTP passwords are generated 

### ISSUE THREAD

**Issue by afattahi54** [freeotp/freeotp-android#186]
When generating a TOTP, the UI shows two progress bar and generates two numbers.
Can you explain what are these ?
How can we configure two have only one generated OTP.

**Comment by npmccallum** [comment]
We did this because we were concerned about the user experience if you happened to click a TOTP right at the end of its window (you'd only see it for the time remaining, which may be too small). We will do something different in the future (yet to be decided).
