### ISSUE TITLE
Why was manual add discontinued?

### ISSUE THREAD

**Issue by castrillon7** [freeotp/freeotp-android#189]
I'm trying to re-add from old commits, but I would like to know why its no longer a feature.
Is it because of some security issues or so?

**Comment by npmccallum** [comment]
1. We didn't feel there was a good use case for it.
2. The code was non-trivial.
3. The code had to be duplicated to multiple platforms (Android, iOS).
4. We already provide this: https://freeotp.github.io/qrcode.html

The plan is to make the above link more mobile friendly and make it trivial to use from within FreeOTP.

Do you see a problem with this plan?

**Comment by castrillon7** [comment]
I see. qrcode is definately easier to use.
Manual was too complex, but, like google auth (which is not as customizable), its still a good idea to have both options.
