### ISSUE TITLE
Change the token display time

### ISSUE THREAD

**Issue by afattahi54** [freeotp/freeotp-android#191]
Please imagine this situation:
There is a token with 30 seconds period but we want to display it for 60 seconds. 

To do this we tried to change the `Token.java` class and add and integer to `end time` to extend it. 

We did it as below:

``` java
      int extraAddedTime = 30000;
      return new TokenCode(getHOTP(counter + 0),
             (counter + 0) * period * 1000,
             (counter + 1) * period * 1000 + extraAddedTime);

```

But it does not work correctly, we wonder if we are doing it in correct way !! 

Can you please help with this ?!

**Comment by npmccallum** [comment]
Why not just make a 60 second token? What are you trying to accomplish?

**Comment by afattahi54** [comment]
Thanks for comment

Well this a long story.
To make it short this the customer requiment that although the token is valid for 30 seconds but they want to display it for 60
Seems quite odd ... But can you help us with this
I tried to change some ui classes but had no luck

**Comment by npmccallum** [comment]
This is a really niche edge case. We do not want to support it.

**Comment by afattahi54** [comment]
I understand but can you guide me which part of source should I tweak

**Comment by npmccallum** [comment]
Currently FreeOTP is not designed for such a feature. I imagine it would be non-trivial to add.
