### ISSUE TITLE
Unable to rearrange tokens

### ISSUE THREAD

**Issue by MikeDawg** [freeotp/freeotp-android#197]
Using FreeOTP v 1.99 (19)

In the old version of FreeOTP, the user was able to sort the OTP keys in any order, with this current version, I don't think it is possible to shift the order of the tokens.

I benefited greatly, by being able to sort the keys in order of use, it would be awesome if that could be brought into this version of FreeOTP.

**Comment by npmccallum** [comment]
@MikeDawg Just click the token image and watch what happens. :)

**Comment by MikeDawg** [comment]
Magical, that's what I was looking for.

Thanks
