### ISSUE TITLE
Project dead? Collaboration with FreeOTP+ planned?

### ISSUE THREAD

**Issue by Krawei** [freeotp/freeotp-android#201]
Dear team,

when I look in the play store I noticed that this app hasn't been updated since two years. It lacks of Android 6 support and doesn't work with its enhanced permission model.

So my questions are:
Will there be a new version of this app in the near future or are you going to collaborate with the FreeOTP+-guys?

Kind Regards,

Krawei

**Comment by bluikko** [comment]
This project indeed seems to be dead, there is https://github.com/helloworld1/FreeOTPPlus/ that is alive and has some (slow) progress.

**Comment by Krawei** [comment]
Thanks for the feedback, will sail to the new project.

**Comment by gelavat** [comment]
There has been a new version of this app in May 2020, after your question, so the project is still active although a new version including some PRs would be welcome.
