### ISSUE TITLE
Support Origin (EA.com)

### ISSUE THREAD

**Issue by palmiche** [freeotp/freeotp-android#204]
When trying to use it with myaccount.ea.com you get a `The token specified was invalid!` toast regardless of the type of device selected.

Please add support for Origin.

**Comment by Natanji** [comment]
Origin is perfectly supported. This is a user error, not a bug.

Here's what you did wrong: Origin will first tell the user to install an authenticator app, and show a QR code for every platform that is just a link to such an app in the respective appstore. If you scan THAT with freeotp, you will get this error message.

If you just click "continue"/"next" below, you will be shown the actual authenticator QR code. Which scans just perfectly in freeotp.

**Comment by palmiche** [comment]
You are absolutely right. I still don't know why I was able to setup the account with Google Authenticator but not FreeOTP but that has to be my mistake.

Thanks.
