### ISSUE TITLE
FreeOTP warns that build is too old

### ISSUE THREAD

**Issue by jbaublitz** [freeotp/freeotp-android#224]
I'm on a Galaxy S10e with Android 10 installed. When I installed FreeOTP for the first time, it warned me that the build for FreeOTP is built for too old of a version of Android and that the app may not function properly. Should I be concerned? Is there any way around this? For the sake of transparency it does seem to be working properly so far.

**Comment by jonathancross** [comment]
This project is abandoned.  Please contribute to https://github.com/freeotp/freeotp-android/issues/207

**Comment by adambkaplan** [comment]
On the iOS side there has been some progress. The Android project is in need of someone to take over active development.

I am currently looking after the Android PRs, but don't have time to take on the big feature work in the Renaissance project.
