### ISSUE TITLE
Is FreeOTP dead/abandoned?

### ISSUE THREAD

**Issue by Hime0698** [freeotp/freeotp-android#226]
Looking at the android store listing and the issues here, the app hasn't been updated in like 4 years and lots of people claim development has been abandoned. However, the renaissance project appears to be active and it looks like someone made a new commit only a couple of months ago. 

TL;DR: What is the current status of development on this app?

**Comment by jonathancross** [comment]
Yes, clearly abandoned.
From what I can see, this is an actively maintained alternative: https://github.com/andOTP/andOTP

**Comment by adambkaplan** [comment]
On the iOS side there has been some progress. The Android project is in need of someone to take over active development.

I am currently looking after the Android PRs, but don't have time to take on the big feature work in the Renaissance project.

**Comment by chris1984** [comment]
Use the Microsoft Authenticator it has cloud backup

**Comment by sanawu** [comment]
> Use the Microsoft Authenticator it has cloud backup

Got the source to it?

**Comment by gelavat** [comment]
There has been commits in May 2020 so it is still active. Last accepted PR was in July 2020.
Maybe there is no big improvement needed for now and this might be the reason of no big update, but it was definitely still active after your question.
