### ISSUE TITLE
How i can import a backup data from device to device?

### ISSUE THREAD

**Issue by Villelmo** [freeotp/freeotp-android#239]
I make a backup from device and i want import this backup another device. The backup save in format .json of FreeOTP+. The FreeOTP+ is incompatible in the new device.  

Name of device: SCH-I435 4.4.2

**Comment by bostrt** [comment]
Hi @Villelmo, I'm not sure if FreeOTP+'s backup is compatible with original FreeOTP (this GitHub repo) since it uses XML and not JSON.
