### ISSUE TITLE
FR: Use QR code to transfer entries

### ISSUE THREAD

**Issue by theking2** [freeotp/freeotp-android#244]
It would be great to transfer entries between devices by generating a QR code for an entry to be readable from an freeotp on another device

**Comment by flibblewibble** [comment]
You can just configure the new device with the secret key that you should be storing securely as a backup anyway

**Comment by theking2** [comment]
thanks, that worked.

Op ma 16 nov. 2020 om 19:46 schreef flibblewibble <notifications@github.com

**Comment by flibblewibble** [comment]
If you store it securely in KeepassXC with the appropriate fields, those fields will be shown in the QR code displayed from KeepassXC and FreeOTP or any other authenticator will pick them up
