### ISSUE TITLE
What manual setup for most 2FA websites?

### ISSUE THREAD

**Issue by gelavat** [freeotp/freeotp-android#256]
What is the setup parameters that we need to select when creating a 2FA code from most websites?

I mean, there are lot of options when we create a new 2FA entry manually, which ones are to be selected so that it works?

Thanks.

**Comment by gelavat** [comment]
After trying a bit, this is what I came up with when adding an entry manually.
It seems most of the websites use this setup by default:

1st field: Name of the website for which you are setting up your 2FA key. It can actually be anything. Better putting the domain name so that you know easily what it is.
2nd field: This field is mandatory but you can just put any text. The best is to put the same as 1st field.
Secret: The secret private key that the website provides you when setting up your 2FA. It is usually a BASE32 code on 16 ASCII characters. There is no upper/lower differentiation, it doesn't matter.
Type: TOTP
Digits: 6
Algorithm: SHA1


Adding a manual entry is very practical so you can immediately backup the secret key and also immediately test it while validating the 2FA.

**Comment by BugReportI** [comment]
It would be nice to add the info in gelavat to a FAQ or help section.

This really helped me out when I could not add it manually and did not want to use the other method.
