### ISSUE TITLE
FreeOTP 2.0 (40): Deleting duplicate keys crashes FreeOTP for good

### ISSUE THREAD

**Issue by github-cygwin** [freeotp/freeotp-android#282]
Reproducer:

In my test case I have 4 keys, system is a Samsung S10 w/ Android 12, latest security updates from November 2022. 

- Create a backup
- In System Settings->Apps->FreeOTP: "Clear Data"
- Start FreeOTP from scratch
- Restore your backup
- Restore your backup *again*
- Now you have all keys twice (why does FreeOTP not check if a key is already present?)
- Delete all duplicate keys

If I delete the *first* set of keys, there's a good chance that the delete action itself crashes FreeOTP.  A dialog appears "Something went wrong with FreeOTP [yada yada]".

If this didn't crash FreeOTP, or if you deleted the second set of duplicates, continue:

- Press any key item

FreeOTP crashes and you're back in the home screen.

From now on, it's impossible to start FreeOTP, it always crashes immediately.  The only way to get it back is by going into the System settings again and clear all data, starting from scratch.

How I got there: For testing I deleted a single key "accidentally", so the idea was to restore it from the backup.  Turns out, the restore function doesn't check for duplicates, so I now had 3 out of 4 key duplicates.  So I deleted the duplicates, tried to use one of the keys and that crashed FreeOTP as described above.

**Comment by justin-stephenson** [comment]
Thank you for the detailed explanation and reproducer steps, this is something which needs to be fixed. Not restoring duplicate tokens may be enough to avoid reaching this broken state.
