### ISSUE TITLE
Code is switched up when the language is RTL

### ISSUE THREAD

**Issue by yanivhs** [freeotp/freeotp-android#284]
The new update makes it useless. 
We were using the old version with sha512 digest, and it was working perfectly. 
With the new version, the most crucial problem is with RTL. 
When the phone language is RTL, the two group of codes switch places, leading to the user entering the wrong code. 
For example, if the code is 123 456
The user sees it as 456 123.

A fix is needed ASAP.

**Comment by justin-stephenson** [comment]
Thank you for reporting this issue, it should be fixable relatively easily.

https://developer.android.com/training/basics/supporting-devices/languages
