### ISSUE TITLE
No icon for Fedora

### ISSUE THREAD

**Issue by jwakely** [freeotp/freeotp-android#311]
With FreeOTP Version 2.0.1 (42) I don't get an icon shown for my Fedora Accounts OTP or for a Twitch OTP, even though it looks like there are files for them in https://github.com/freeotp/freeotp-android/tree/master/mobile/src/main/res/drawable

**Comment by justin-stephenson** [comment]
The token issuer field must match the string value following `brand_` mapping table provided here,  https://github.com/freeotp/freeotp-android/blob/master/mobile/src/main/res/values/colors.xml

The intention is for users to submit PRs to add to this mapping table as needed. If you can provide the issuer field which is used when adding tokens for Twitch/Fedora/etc, then I will add them those mappings this table.

If you touch the token icon, press the pencil and change the bottom field (issuer) to `fedora` then it should automatically update the icon.

**Comment by jwakely** [comment]
Thanks for the explanation. I'll see if I can submit PRs for those mappings then...

**Comment by jwakely** [comment]
I removed the twitch token from the app and set up a new one by scanning a QR code, and the icon appeared that time.

Maybe the missing icons are just an artefact of creating those tokens in the old version of the app, and there's actually no issue here.

**Comment by justin-stephenson** [comment]
> I removed the twitch token from the app and set up a new one by scanning a QR code, and the icon appeared that time.
> 
> Maybe the missing icons are just an artefact of creating those tokens in the old version of the app, and there's actually no issue here.

Okay thanks for checking, let me know if you think there is any issue here.

**Comment by jwakely** [comment]
The twitch icon appeared after recreating it, and I fixed the fedora one by editing it as you suggested above, so let's close this.

**Comment by albeec13** [comment]
> The token issuer field must match the string value following `brand_` mapping table provided here, https://github.com/freeotp/freeotp-android/blob/master/mobile/src/main/res/values/colors.xml
> 
> The intention is for users to submit PRs to add to this mapping table as needed. If you can provide the issuer field which is used when adding tokens for Twitch/Fedora/etc, then I will add them those mappings this table.
> 
> If you touch the token icon, press the pencil and change the bottom field (issuer) to `fedora` then it should automatically update the icon.

I read the BRANDING.md file hoping to find out what would need to be done to add more services' icons, but from what I can tell, the only way to do so is for them to be added to FontAwesome's database online. That's all well and good, but end users have almost no ability to add fonts to that site, as they do not accept icon submissions that aren't part of a paid request or initiated by their own staff based on popular demand.

I noticed there are many fa_*.xml files in `./src/main/res/drawable` that seem to be pulled from Fontawesome and packaged with the FreeOTP apk. Does the app pull these icons from the package, or does it actually hit Fontawesome's API to retrieve them? It's hard to tell from the code, but it looks like it only pulls files from the package.

If the latter is true, will FreeOTP accept user PR's for adding more services' icons to that folder, or do we have to wait decades for someone at Fontawesome to release them first before they can be copied into the FreeOTP codebase for use?

**Comment by justin-stephenson** [comment]
> @justin-stephenson said:
> 
> > The token issuer field must match the string value following `brand_` mapping table provided here, https://github.com/freeotp/freeotp-android/blob/master/mobile/src/main/res/values/colors.xml
> > The intention is for users to submit PRs to add to this mapping table as needed. If you can provide the issuer field which is used when adding tokens for Twitch/Fedora/etc, then I will add them those mappings this table.
> > If you touch the token icon, press the pencil and change the bottom field (issuer) to `fedora` then it should automatically update the icon.
> 
> I read the BRANDING.md file hoping to find out what would need to be done to add more services' icons, but from what I can tell, the only way to do so is for them to be added to FontAwesome's database online. That's all well and good, but end users have almost no ability to add fonts to that site, as they do not accept icon submissions that aren't part of a paid request or initiated by their own staff based on popular demand.
> 
> I noticed there are many fa_*.xml files in `./src/main/res/drawable` that seem to be pulled from Fontawesome and packaged with the FreeOTP apk. Does the app pull these icons from the package, or does it actually hit Fontawesome's API to retrieve them? It's hard to tell from the code, but it looks like it only pulls files from the package.

Those fontawesome icon files are pulled manually and included in the FreeOTP build.
> 
> If the latter is true, will FreeOTP accept user PR's for adding more services' icons to that folder, or do we have to wait decades for someone at Fontawesome to release them first before they can be copied into the FreeOTP codebase for use?

I am open to accepting PR for adding more icons to this directory, especially if FontAwesome does not accept non-paid external submissions for new icons. I would prefer to only add icons which could be used by many FreeOTP users, not an individual use case. It would be great if the submitted icons follow the [FontAwesome Icon guidelines](https://fontawesome.com/v5/docs/web/use-kits/icon-design-guidelines)

The FontAwesome icon set pulled into FreeOTP may be outdated, you might check if new available FontAwesome icons could suit your needs and are already available.

**Comment by albeec13** [comment]
That sounds great. I have a handful that I'm sure are not obscure (think Nintendo, itchi.io, Wyze, etc.), which I've pulled from the original companies' own svg files and updated to match the format of the Android drawables already existing in the codebase.

A few of them are narrower vertically than the 16x12 recommendations from fontawesome, but should still match well with the app. I should be able to open a PR soon.

**Comment by albeec13** [comment]
FYI: https://github.com/freeotp/freeotp-android/pull/316
