### ISSUE TITLE
How to see remaining seconds?

### ISSUE THREAD

**Issue by johnaweiss** [freeotp/freeotp-android#312]
Hello,

FreeOTP is great!

But, your new interface doesn't show remaining seconds. I've had the experience of typing the code, and then the code times out before i'm finished typing. 

Is there a way to show seconds remaining?

thx!

**Comment by justin-stephenson** [comment]
Hello,

Thank you for your comments.

The progress bar decreasing is intended to show the end time of validity for the displayed token code. That said there are some improvements which would improve the UX here https://github.com/freeotp/freeotp-android/issues/273

Unfortunately I have not had time to implement this, PRs are welcome.

**Comment by johnaweiss** [comment]
I cannot seer a progress bar. Where is the progress bar?

Your previous version showed remaining time.

**Comment by justin-stephenson** [comment]
> I cannot seer a progress bar. Where is the progress bar? Your previous version showed remaining time.
> […](#)

Do you not see the progress bar at the bottom of the token border? Do you have animations disabled in your phone settings? See screenshot attached.


![Screenshot_20230223-121301_FreeOTP](https://user-images.githubusercontent.com/13416969/220980479-36888cc9-5dd4-4d82-9a61-aeb5ca598357.png)

**Comment by johnaweiss** [comment]
I don't get that progress bar.
I see a solid blue line that is always 100% width.
Nothing moves or changes.
I cannot take a screenshot, it's not allowed.

**Comment by justin-stephenson** [comment]
This can happen if animations are disabled on the device - Can you check these settings?

In System - Developer Options, Window/Transition/Animator scale

**Comment by johnaweiss** [comment]
Here are my settings. What should I change?

**Comment by justin-stephenson** [comment]
> Here are my settings. What should I change?


I do not see any settings provided in your last comment

**Comment by johnaweiss** [comment]
![image](https://user-images.githubusercontent.com/53209681/221038626-3909b2d1-9df8-4883-b26c-367ad4e84695.png)

**Comment by justin-stephenson** [comment]
> ![image](https://user-images.githubusercontent.com/53209681/221038626-3909b2d1-9df8-4883-b26c-367ad4e84695.png)

The three settings showing as `Animation off` should be changed to Animation scale #x - I believe the default is `1x` for Window/Transition/Animator scale
