### ISSUE TITLE
`v2.0.1` F-Droid Release Needed

### ISSUE THREAD

**Issue by quinndiggity** [freeotp/freeotp-android#314]
Hey there 👋🏻 The updates to the app have been fantastic, and really appreciated 👍🏻

I'm finding that [Steam Guard codes](https://github.com/freeotp/freeotp-android/pull/105) seem to be affected by the same [RTL issue](https://github.com/freeotp/freeotp-android/issues/284) that was [fixed](https://github.com/freeotp/freeotp-android/pull/296) in [the v2.0.1 release](https://github.com/freeotp/freeotp-android/releases/tag/v2.0.1), but `v2.0.1` hasn't been pushed to [F-Droid](https://f-droid.org/packages/org.fedorahosted.freeotp/#latest) (or *far* less importantly, gplay).

It would be greatly appreciated if a new release of the APK could be cut, signed, and uploaded to F-Droid; specifically, so as to avoid needing to do the dance needed to preserve the applications database when locally building and signing an APK to be installed.

**Comment by quinndiggity** [comment]
To clarify the `RTL issue` I'm referring to - an example valid code as generated by [Bitwarden's support for Steam Guard otp](https://bitwarden.com/help/authenticator-keys/#steam-guard-totps) as well as Steam Guard itself:

`ABCDE`

versus the codes generated by FreeOTP:

`EDCBA`

**Comment by justin-stephenson** [comment]
Hi @quinndiggity Thanks for your feedback. FreeOTP `2.0.1` is available on the Google Play store currently. Do you know why it has not been detected by F-Droid ? As I understand it, F-Droid should automatically detect the new version to build in the F-Droid repo.

I'll look into it more if you, or someone else is unsure why it is not working.

**Comment by quinndiggity** [comment]
Thanks for the quick response, @justin-stephenson - I suspect it is related to a missing version bump in https://github.com/freeotp/freeotp-android/blob/v2.0.1/mobile/build.gradle#L10

https://f-droid.org/en/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update

https://f-droid.org/en/docs/Build_Metadata_Reference/#UpdateCheckMode

But I'd need to dig further

**Comment by quinndiggity** [comment]
Seems both `v2.0.0` and `v2.0.1` have `versionCode 24`:

https://github.com/freeotp/freeotp-android/blob/v2.0/mobile/build.gradle#L9
https://github.com/freeotp/freeotp-android/blob/v2.0.1/mobile/build.gradle#L9

Which matches the version on F-Droid https://f-droid.org/packages/org.fedorahosted.freeotp/#latest
![image](https://user-images.githubusercontent.com/10092236/224146364-a7476d0a-1119-49c3-bf1f-e0902fee663f.png)

**Comment by justin-stephenson** [comment]
Thank you, the versionCode is an internal version number according to [Android docs](https://developer.android.com/studio/publish/versioning) side - so it was not bumped as part of source control. I will issue a PR to bump this and hopefully F-Droid will pick it up soon.

**Comment by justin-stephenson** [comment]
I merged https://github.com/freeotp/freeotp-android/pull/315 though I'm still not exactly sure why this is needed as the built APK does contain the bumped version numbers(done locally), it was only not reflected in the github repo build.gradle.

Let's keep this open to make sure it is detected by F-Droid in a couple days hopefully.

**Comment by quinndiggity** [comment]
@justin-stephenson , yeah, this will require a new tag, or recreating the `v2.0.1` tag:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12719#note_1308225111

after that, it'll be picked up in ~12 hours:

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/12719#note_1308226425

**Comment by justin-stephenson** [comment]
Done. Thanks for your help on this @quinndiggity !

https://github.com/freeotp/freeotp-android/releases/tag/v2.0.1

**Comment by justin-stephenson** [comment]
@quinndiggity are you good to close this? It looks to be updated on F-Droid now https://f-droid.org/en/packages/org.fedorahosted.freeotp/
