### ISSUE TITLE
Backup from file does not recreate OTPs

### ISSUE THREAD

**Issue by DerNils-git** [freeotp/freeotp-android#318]
Hi everyone,

I created a file backup of the OTPs in the FreeOTP App using the `Backup` option.
 (I am not sure about the Version but I think it should be >2.0.0).
Now my phone broke and I like to recover my OTPs on a different phone from the backup file.

I can choose the `Restore` option in the app, choose the backup file and enter the pw without problem.
But the OTPs which should be stored are not recovered. The App remains empty.

The backup file is not empty. I could identify the `label` and `issuerInt` sections which I would expect in the file.

If I create a new [example OTP](https://freeotp.github.io/qrcode.html), create a backup file, delete the OTP from the app and recover it from the backup file, the expected OTP appears again.

Is the backup not compatible between different phones or might there be a different problem?

I would appreciate some help on the problem.

Thanks in advance.

**Comment by justin-stephenson** [comment]
Closing as duplicate.
