### ISSUE TITLE
Re-enable Travis CI or migrate to another CI service?

### ISSUE THREAD

**Issue by PeterDaveHello** [freeotp/freeotp-android#342]
Since June 15th, 2021, the building on travis-ci.org is ceased, should use travis-ci.com instead.

The badge in README now shows build status unknown, and the link in README https://travis-ci.org/freeotp/freeotp-android will now be redirected to https://app.travis-ci.com/freeotp/freeotp-android, which shows:

> We couldn't display the repository freeotp/freeotp-android
> 
> This repository may not exist or you may need to use another account to have access to it 

I personally continue using Travis CI as they'd kindly provide the credits(https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source), and the migration will be easier compared to migration to another platform.

**Comment by justin-stephenson** [comment]
I would prefer to migrate to Github actions, a simple workflow to build the gradle project would be a good starting point.

**Comment by PeterDaveHello** [comment]
It looks like it's done already: https://github.com/freeotp/freeotp-android/commits/master/.github/workflows/build.yml; then I think we can drop the Travis CI config, right?
