### ISSUE TITLE
FreeOTP crashes on launch

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#35]
**Reported by airwave on 1 Aug 2014 13:47 UTC**
Yesterday I installed FreeOTP and added some OTPs to it. Today when I try to launch it, I get "Unfortunately, FreeOTP has stopped." Attached is a logcat for the crash. Please let me know if there's any more information I can help with.

**Comment by npmccallum** [comment]
**Comment by airwave on 2 Sep 2014 11:12 UTC**
This issue still exists in 1.5.

**Comment by tesfabpel** [comment]
At least for me, the stack trace says:

```
java.lang.RuntimeException: Fail to get camera info
at android.hardware.Camera._getCameraInfo
at android.hardware.Camera.getCameraInfo
at org.fedorahosted.freeotp.add.ScanActivity.findCamera
at org.fedorahosted.freeotp.add.ScanActivity.haveCamera
at org.fedorahosted.freeotp.MainActivity.onCreateOptionsMenu
at ...
```

**Comment by joekir** [comment]
@npmccallum do you have the logcat output for this, so we can reproduce the crashing behavior?

**Comment by npmccallum** [comment]
@joekir It does not appear that the logcat output survived the trac => github migration.

**Comment by joekir** [comment]
I guess this ticket should be closed out then. 
Unless the original submitter is available for comment?
