### ISSUE TITLE
Add Tutanota icon

### ISSUE THREAD

**Issue by WebSnke** [freeotp/freeotp-android#357]
There is no icon for Tutanota in FreeOTP. I would love to resolve this issue but I don't really know how 
I would add a new icon for such an Android app.

@justin-stephenson

**Comment by justin-stephenson** [comment]
Perhaps you can look at https://github.com/freeotp/freeotp-android/pull/316 for inspiration or maybe @albeec13 could help you with the steps needed?

**Comment by albeec13** [comment]
Threw something together quickly and opened a PR. Please check that it looks OK on mobile, as I am not set up to build/test these. Thanks!
