### ISSUE TITLE
Security concern with new ios device

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#36]
**Reported by mhyzon on 1 Aug 2014 18:24 UTC**
I am not sure if this is actually a problem, but I wanted to bring it up. 

I recently got a new iphone so I backed up my old iOS device and then restored to the new one.  FreeOTP worked just fine on the new device as well as the old device.

Obviously, the seeds, etc are stored in in the backup file.  IIRC, when I upgraded devices with google authenticator, I needed to create a new token, as the seeds were only stored locally on the device.

As much as this is a usability win, I would think it is a security fail since a fundamentally new device should be a fundamentally new token and get a new seed, IMO.

IE, I can imagine a user losing a device, reinstalling from backup, and never reporting the lost device and never disabling the 'old' token, thus the lost/stolen device is still out there and valid (more a problem for TOTP than HOTP, but still)

**Comment by npmccallum** [comment]
**Modified by mhyzon on 1 Aug 2014 18:24 UTC**

**Comment by npmccallum** [comment]
**Comment by npmccallum on 19 Aug 2014 14:18 UTC**
We plan to solve this with encryption of token data.

**Comment by bufferoverflow** [comment]
can be closed, it is here https://github.com/freeotp/freeotp-ios/issues/36
