### ISSUE TITLE
Version 2.0.3 is not available in Play Store and F-Droid

### ISSUE THREAD

**Issue by joggee-fr** [freeotp/freeotp-android#377]
The [2.0.3 release](https://github.com/freeotp/freeotp-android/releases/tag/v2.0.3) has been published here about one month ago. However, I can't see this new version nor in [Play Store](https://play.google.com/store/apps/details?id=org.fedorahosted.freeotp) nor in [F-Droid](https://f-droid.org/fr/packages/org.fedorahosted.freeotp/). Am I looking at the right places?

**Comment by justin-stephenson** [comment]
Hi, sorry for that. This version was submitted to Google for review but then I had to go back and click "Publish" to deliver it.

I just did this so you should see it appear in the Play Store in the coming hours

**Comment by joggee-fr** [comment]
Thanks a lot @justin-stephenson, it is good for me now.
