### ISSUE TITLE
How to set it up for Reddit?

### ISSUE THREAD

**Issue by Th3-A6add0n** [freeotp/freeotp-android#382]
How do you set it up for Reddit manually? Without the QR.
This app doesn't have the feature to scan QR from gallery, so if anybody who doesn't have 2 devices can't even setup the 2fa without relying on adding tokens manually & your guides don't make it easy to know how to set it up manually.

**Comment by joggee-fr** [comment]
If you click on the "Add" icon, then on the "Pen" one, you can add a token manually. Is it what you are looking for?

**Comment by Th3-A6add0n** [comment]
> If you click on the "Add" icon, then on the "Pen" one, you can add a token manually. Is it what you are looking for?

No no, that I know, I know how to add token manually but just adding the ticket & website name doesn't work. Like for example, for Twitter you're required to add @Username, for email service you're required to add email@example.com but for Reddit I've tried everything & nothing works, the Reddit doesn't accept the code whatsoever. I've tried adding "Username", "@Username" "reddit.com/username", "username@reddit.com", "reddit.com/user/username" and so on.

**Comment by johnnynoone** [comment]
> This app doesn't have the feature to scan QR from gallery

Try a fake camera app which pretends to take an image, but just opens an image from gallery. GalleryCam is one such application.

**Comment by Th3-A6add0n** [comment]
> > This app doesn't have the feature to scan QR from gallery
> 
> Try a fake camera app which pretends to take an image, but just opens an image from gallery. GalleryCam is one such application.

And how do you suggest I use that with FreeOTP? You do know that FreeOTP has built in scanner, RIGHT? That's the whole point ain't it? The built in scanner/camera doesn't let you choose QR code from gallery & 3rd party apps are of NO USE here.

**Comment by johnnynoone** [comment]
Oh, right. Sorry for being dumb. I guess you could use another device to display the QR code.

Actually, I looked up an example QR code from Reddit 2FA. The URL looks like this: `otpauth://totp/Reddit:mundoconjulio?secret=PTG6CROZMCHTSWZ62SYPBNSHXWXWLUVG&issuer=Reddit`.

**Comment by Th3-A6add0n** [comment]
> Oh, right. Sorry for being dumb. I guess you could use another device to display the QR code.
> 
> Actually, I looked up an [example QR code from Reddit 2FA](https://ciberprotector.com/guias/como-activar-2fa-en-reddit/). The URL looks like this: `otpauth://totp/Reddit:mundoconjulio?secret=PTG6CROZMCHTSWZ62SYPBNSHXWXWLUVG&issuer=Reddit`.

Tried that (my 1st try was this only) didn't work at all 🥲🥲
Tried both, TOTP & HOTP

**Comment by justin-stephenson** [comment]
Hi, what information does reddit give you manually to enter? **please modify the secret value** before including.

You should be able to enter the fields manually into FreeOTP. Or generate a QR code with https://freeotp.github.io/qrcode.html or https://stefansundin.github.io/2fa-qr/

**Comment by Th3-A6add0n** [comment]
> Hi, what information does reddit give you manually to enter? **please modify the secret value** before including.
> 
> You should be able to enter the fields manually into FreeOTP. Or generate a QR code with https://freeotp.github.io/qrcode.html or https://stefansundin.github.io/2fa-qr/

Well, reddit just wasn't accepting the otp code. I finally did the QR scan using 2 devices. But still, using an image from gallery is always helpful & it should be a feature.

**Comment by johnnynoone** [comment]
@Th3-A6add0n Opening images of QR codes is definitely useful. There's already an issue for it: #370.
