### ISSUE TITLE
otpauth://totp/%D0%9D%D0%B0%D1%83%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9%20%D1%86%D0%B5%D0%BD%D1%82%D1%80%20%D0%B4%D0%B8%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F%20adl.mil.gov.ua%3Atemp9413?issuer=%D0%9D%D0%B0%D1%83%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9%20%D1%86%D0%B5%D0%BD%D1%82%D1%80%20%D0%B4%D0%B8%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F%20adl.mil.gov.ua&secret=BWHT6NWCIT5BLKMA

### ISSUE THREAD

**Issue by Rostislavtop** [freeotp/freeotp-android#404]
otpauth://totp/%D0%9D%D0%B0%D1%83%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9%20%D1%86%D0%B5%D0%BD%D1%82%D1%80%20%D0%B4%D0%B8%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F%20adl.mil.gov.ua%3Atemp9413?issuer=%D0%9D%D0%B0%D1%83%D0%BA%D0%BE%D0%B2%D0%B8%D0%B9%20%D1%86%D0%B5%D0%BD%D1%82%D1%80%20%D0%B4%D0%B8%D1%81%D1%82%D0%B0%D0%BD%D1%86%D1%96%D0%B9%D0%BD%D0%BE%D0%B3%D0%BE%20%D0%BD%D0%B0%D0%B2%D1%87%D0%B0%D0%BD%D0%BD%D1%8F%20adl.mil.gov.ua&secret=BWHT6NWCIT5BLKMA

**Comment by vollkorn1982** [comment]
@Rostislavtop That TOTP is now compromised. You should re-setup 2FA with your account and make sure, that you get a new secret.

**Comment by juleskers** [comment]
> adl.mil.gov.ua

Oh dear lord... If this is Ukrainian military OpSec, the Russians will have a field day...
