### ISSUE TITLE
Scanning QR code on iOS produces no result

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#44]
**Reported by oliversalzburg on 6 Oct 2014 09:10 UTC**
When I scan this QR code on Android, the entry will be imported just fine. On iOS the camera will disappear and no entry will be added to the list.

[[Image(http://i.imgur.com/11WpJU9.png)]]

**Comment by bufferoverflow** [comment]
This issue can be closed, its over here https://github.com/freeotp/freeotp-ios/issues/44
