### ISSUE TITLE
Copied to clipboard message covers the code

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#49]
**Reported by goldmann on 28 Nov 2014 13:36 UTC**
When we have many tokens that fill the entire screen on a phone, when we click to get the code generated on the last one on tje screen, the "copied to clipboard" message hides the code for a couple of seconds.

I should be able to read the code immediately.

**Comment by npmccallum** [comment]
**Comment by tyfox on 8 May 2016 23:59 UTC**
This has also been bugging me for a while.

I'm not familiar with android dev nor the codebase of freeotp but I'm proposing a patch (attached).

This should display the "Copied to clipboard" toast on the top half of the screen if the code is in the bottom half.

**Comment by ehuggett** [comment]
The root cause appears to be the user does not want/need the code in their clipboard if they want to read it, moving the message is only addressing the symptom

**Comment by andrewjswan** [comment]
Plz add a customization, in the settings, copy or no key in the clipboard.

**Comment by npmccallum** [comment]
I plan to address this shortly. But we are using a different mechanism to avoid the complexity of having a setting. Namely, clicking the token will display the token. But choosing to "share" the token will allow the user to choose "clipboard" among other options. This is unintrusive, simple, state free and discoverable.

**Comment by basicmaster** [comment]
@npmccallum I was wondering if this going to be merged soon...
