### ISSUE TITLE
Custom icons are not persistent

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#51]
**Reported by flasheater on 12 Dec 2014 23:48 UTC**
Possibly related to #32. 
1. Set custom Icon using the Google Photos app
2. Switch to another app and switch back
   Icon is now back to default. 

Android Cyanogenmod 11
Nexus 5

**Comment by npmccallum** [comment]
**Comment by jfreak on 22 Jun 2015 09:19 UTC**
I think it might be persisted. But when trying to open it something happens.
I see this in my logcat:
W/ActivityManager(  745): Permission Denial: opening provider com.google.android.apps.photos.contentprovider.MediaContentProvider from ProcessRecord{1339b35b 15646:org.fedorahosted.freeotp/u0a82} (pid=15646, uid=10082) that is not exported from uid 10065

Maybe something happens with the URL. The icons I selected a few versions back show up nicely.

Nexus 5. Stock 5.1.1

**Comment by npmccallum** [comment]
**Comment by jfreak on 18 Aug 2015 18:30 UTC**
I tried to debug this a bit further.

It seems the URIs look similar to this content://com.google.android.apps.photos.contentprovider/0/1/content%3A%2F%2Fmedia%2Fexternal%2Fimages%2Fmedia%2F75209/ACTUAL when selected from the Google Photos app.

From what I understand this URI is only valid from the process that initially got it. That means that as soon as you leave the app again it will get a new UID and therefore the URI is no longer valid.

A possible workaround is discussed here: http://stackoverflow.com/questions/30527045/choosing-photo-using-new-google-photos-app-is-broken.

As I see it there are three possible solutions. 
One is to cache a copy of the image locally before the Token is persisted and persist it with a URI to the local cache. 
The other is to get the URI through some other app that returns the URI from the file system.
The third option is to get the URI for the file system by decoding the URI from Google Photos.

The first solution is probably the cleanest. Then FreeOTP will not be dependent on files on the filesystem anymore. The files can be deleted but the icon is still available for FreeOTP from its local copy.

**Comment by npmccallum** [comment]
**Comment by jfreak on 16 Oct 2015 06:59 UTC**
Until the patch gets accepted I found another workaround: http://blog.vester.org/2015/10/freeotp-icon-fix.html
Basically you have to extract the tokens from a backup and edit the references to the images and then restore a backup with the changes.

**Comment by npmccallum** [comment]
**Comment by mattdm on 10 Dec 2015 12:33 UTC**
On the almost anniversary of this issue... any chance of a new release with this fix? I use FreeOTP for a number of different systems, and this would be really nice to have.

**Comment by npmccallum** [comment]
**Comment by bjabram on 27 Jan 2016 12:22 UTC**
According to the Google Play store this was fixed in v1.5 (17) but I am still experiencing this problem. I can choose the icon but when I reopen the app the icons are missing. Nexus 5, Android 6.0.1

**Comment by npmccallum** [comment]
**Comment by jonfen on 15 Feb 2016 10:23 UTC**
Yes, still an issue on Nexus 5, Android 6.0.1

**Comment by npmccallum** [comment]
**Comment by jfenal on 5 Apr 2016 08:04 UTC**
Still an issue on a Samsung GS6, Lollipop, using images local to the phone.

**Comment by npmccallum** [comment]
**Comment by whereisaaron on 25 May 2016 16:47 UTC**
Still an issue with v1.5 (17) on Samsung S6 with Android 6.0.1. This problem didn't occur with the same version on Android 5.1 on Samsung S6. Appears to be a Marshmallow incompatibility.

Old icons selected before upgrading to Android 6 are still there and persistent. But new icons you add or edit under Android 6 do not get persisted past a restart.

The icon doesn't disappear until the app is restarted. Switching back and forth to the app while it is still runnning and in memory the icon is still there.

**Comment by npmccallum** [comment]
**Comment by corppneq on 10 Jun 2016 23:47 UTC**
+1
(Android 6.0.1 - Build MTC19T - Nexus 5X)

**Comment by npmccallum** [comment]
**Comment by mattdm on 15 Sep 2016 14:42 UTC**
Still want :)

**Comment by Maxqia** [comment]
+1

**Comment by jaredhocutt** [comment]
+1

**Comment by albeec13** [comment]
Can someone comment on when this fix will hit the Play Store? The last update appears to be from 2016. Barring that, does FDroid have a newer version? (A cursory check did not indicate that was the case.)

**Comment by ahoulgrave** [comment]
+1

**Comment by sarahtisdale** [comment]
Is this fixed?  I just installed FreeOTP Version 1.5 (17) and it seems to have this exact problem.  Thanks!

**Comment by gobater** [comment]
Still an issue in Version 17 (1.5), Android Pie

**Comment by mikelsr** [comment]
> The issue seems to be related to Google Fotos. Install Another Image Gallery app (e.g. Simple Gallery) and use it to select the picture. It works fine, while Google Fotos suffers the issues mentioned above

Right on point, icons stopped resetting after selecting them with a different gallery app. Thank you.
