### ISSUE TITLE
barcode won't scan on CM12/android5

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#52]
**Reported by chrismurphy on 12 Jan 2015 03:06 UTC**
I've upgraded a phone to cm-12-20150111 which is Android 5.0.2, and freeotp won't scan a bar code. A UI to scan a bar code appears, activating the camera and shows the barcode within the square region, but then nothing happens. Did regression testing with Google Authenticator, which requires Barcode Scanner by ZXing Team and that combination does work. Prior to the upgrade the phone had CM11 / Android 4.4.4 and freeotp worked.

**Comment by PanderMusubi** [comment]
Is this still relevant as CM is discontinued in 2016? Otherwise, please close this issue.
