### ISSUE TITLE
Manual add UI fields are confusing

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#55]
**Reported by xlynx on 9 Feb 2015 03:36 UTC**
The first two fields when adding an entry are unlabelled text boxes with example background text:

joe@example.com
18c5d06cfcbd4927

"18c5d06cfcbd4927" suggests the secret goes here, and because it's a required field it's all very confusing.

As far as I can see, these fields roughly mean "service name" and "username". Therefore I would suggest the background text read something more like:

My account
joe@example.com

A small change but would do a lot for usability.

**Comment by lostinlight** [comment]
Thanks for the app, and for this issue. 
I haven't used similar app before and tried typing email and password instead of service name and username, and couldn't understand why it didn't work. This issue helped.

**Comment by CanRau** [comment]
uhu thanks for the hint 👍

**Comment by lislis** [comment]
Hey! I'm working on an [2FA implementation](https://github.com/diaspora/diaspora/pull/7751) myself and wanted to display all the information needed to manually enter a new token in FreeOTP and I was quite surprised how many options people are supposed to enter (also by how the fields are labelled).
 
A user flow I know from other clients and that I find more helpful is first entering the secret, then prompting the username and the app name.
