### ISSUE TITLE
Add Option to Disable Copying Code to Clipboard

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#58]
**Reported by gfactor on 16 Feb 2015 00:28 UTC**
Can you provide an option to disable the automatic copying of OTP codes to the clipboard? I realize that the autocopying of OTP codes can be a great help for most users, but I usually don't use my OTP codes on my Android device. This makes the autocopying of codes a potential security hazard for me without any benefit.

**Comment by adonis28850** [comment]
Any update on this?
