### ISSUE TITLE
Toast blocks token visibility

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#61]
**Reported by oliversalzburg on 25 Mar 2015 12:28 UTC**
If you have enough entries to fill the whole screen, the "Token copied to clipboard" toast blocks the view to the token that you just generated.

This is inconvenient, because I don't care about it being copied to the clipboard and I know it was copied to the clipboard after seeing the toast for the first couple of times and now I just want to read the token so I can login.

**Comment by hiqua** [comment]
Same as #49.
