### ISSUE TITLE
[RFE] Make the clipboard integration non-default

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#63]
**Reported by dpal on 7 May 2015 22:49 UTC**
Add a way to disable clipboard integration.

**Comment by Slamdunk** [comment]
Thumb up

**Comment by amilopowers** [comment]
I would love to get that feature as well. I've read that malicous apps could read the clipboard and use the OTP. Our minds should be able to memorise that short code for a few seconds.

**Comment by amilopowers** [comment]
Or if not default provide at least the option to opt-out.
