### ISSUE TITLE
Every OTP generation results in true dialer number search

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#66]
**Reported by coolsvap on 1 Jul 2015 08:18 UTC**
Everytime I generate an otp the true dialer number search is invoked by default.

**Comment by npmccallum** [comment]
**Comment by coolsvap on 1 Jul 2015 15:32 UTC**
I have found the root cause for the issue. After every OTP generation, the OTP is copied by default which leads to this issue. If I turn off the true dialer service cron job to actively monitor numbers in clipboard, the issue does not come.

**Comment by ehuggett** [comment]
Wow, If I understand correctly, you have a service running on your device that will leak the contents of your clipboard to a 3rd party if it looks like a telephone number? (and this is not an uncommon service for a user to have installed).

This sounds like a very compelling reason not to copy OTP codes into the clipboard by default (there is currently _no_ method to avoid this happening with freeOTP as far as I can tell).

I would suggest being able to copy the code from the context menu for that entry (unlikely to happen by accident), or by tapping again on a entry once the OTP is displayed. 

The user should also be cautioned that the clipboard may not be secure/safe as I don't think its reasonable to expect them to expect this kind of risk, ie true dialler. (I certainly falsely assumed no honest application would be interested in my clipboard, much less transferring its contents to a 3rd party)

I very rarely use the OTP code on the device that freeOTP is running on, and I suspect this use is not uncommon. The pull request I just referenced this issue from would only be a band aid, but if its ready at least it can be deployed quickly
