### ISSUE TITLE
Can not add second Slack account

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#67]
**Reported by pla on 16 Jul 2015 12:20 UTC**
When I scan the QR for a second Slack (https://slack.com/) account FreeOTP doesn't add a new entry. FreeOTP seems to think it is the same as the first Slack account (guessing). My phone is a Asus Zenfone 2 model ASUS_Z00AD. I tried this with ADB logcat running but I didn't see anything interesting. Thanks, PLA

**Comment by duelle** [comment]
I also have the said issue. Adding the first Slack Team QR Code works just fine, but adding the second does not work.

**Comment by wesdawg** [comment]
I had a similar issue scanning a QR for a third Slack account (16th token). The QR matched and then the app went back to the main list without adding the token.

I renamed the previous two Slack account tokens from the default so I'm not entirely sure if this is the same issue.

**Comment by PanderMusubi** [comment]
More sites where one can have multiple accounts result in this problem with FreeOTP. E.g. the app Authy solves it by enabling adding more codes per site. Please, fix his for this app.

**Comment by gbouthenot** [comment]
Even if I modify user, and description, adding a second TOTP secret results in nothing.
It should either: add a new code, tell the user a previous code is already known add if he wants to replace it or add a new code.

**Comment by whiteinge** [comment]
A workaround in the meantime is to change your email address in each Slack workspace.

If you're using an email provider like Gmail that supports the `<address>+<modifier>@example.com` format then you can still use your single email account for each one. I was able to get all my Slack workspaces added to FreeOTP by using `<my-address>+<workspace-name>@gmail.com` in each.
