### ISSUE TITLE
Better handling of adding a duplicate token

### ISSUE THREAD

**Issue by npmccallum** [freeotp/freeotp-android#7]
**Reported by npmccallum on 13 Dec 2013 14:49 UTC**
Currently if the user attempts to add a token that already exists, we silently ignore it. Instead, we should:
- detect the token already exists
- prompt the user for permission to overwrite (with stern warning)

There is no security issue here, but it would be helpful to have a better UI.

**Comment by npmccallum** [comment]
**Modified by npmccallum on 10 Jan 2014 22:00 UTC**

**Comment by AlD** [comment]
It would be great if you could actually add multiple accounts for the same web page. This currently doesn't seem to work.

**Comment by absorber** [comment]
Currently this is very problematic if you are trying to create multiple 2FA wallets in the [Electrum wallet](https://github.com/freeotp/freeotp-android/issues/7). While the OTP secret is different, the metadata is the same as the previous OTP secret. Currently the app doesn't add the secret and displays no information, so the user might be under the assumption that it has been added (with overwrite of the previous secret) or not.

IMO, the app should ask whether the user would like to overwrite, edit the metadata (and once edited, add the new secret) or cancel.
