### ISSUE TITLE
New keys aren’t persisted anymore for (yet) unknown reason

### ISSUE THREAD

**Issue by bmenant** [freeotp/freeotp-android#81]
FreeOTP Version 1.5 (17) installed from F-Droid on a CyanogenMod 13.0-20160820.

I had 7 keys I added flashing code from various 2-factors auth services, working fine since a year or so.

Then, I wanted to add a new one. It did work: flashed the QR code, generated a first code, no error... I eventually closed FreeOTP app and went back to other activities.

The day after, I wanted to log again in that service. I launched FreeOTP. The 7 previously added keys were there, but the new one was just missing.

I tried to add new keys again with two other services, and it failed the exact same way: close the app and new keys are lost.

Might it be related to the fact I somehow recently changed my smartphone for a newer one? I had made a back up of the `tokens.xml` file and copied it onto my new device. It had worked fine until I tried to add a new key.

I’ve checked out access rights but everything looks fine, AFAIK. The datetime of last modification never changed, though.

What do you think @npmccallum? How can I help debugging?

**Comment by bachp** [comment]
I think this is a duplicate of #77

**Comment by bmenant** [comment]
@bachp You’re right. Thus, I better close this duplicate issue.
