### ISSUE TITLE
Hide TOTP code on second tap

### ISSUE THREAD

**Issue by roweryan** [freeotp/freeotp-android#84]
I need to be able to hide a TOTP code once I have entered it, could you consider adding this functionality?

**Comment by npmccallum** [comment]
Why do you want this? Can you help me understand what you are protecting against with this feature?

**Comment by roweryan** [comment]
When I am setting up a new machine I need to keep the FreeOTP app open for a while, but at the same time I want to keep the amount of time these codes are visible to the minimum. So I'd like to be able to hide the ever-changing TOTP for an account once I am done.

**Comment by npmccallum** [comment]
I don't think this provides any additional security. The TOTP should only be valid for a single use. So having someone see the code after you use it doesn't matter.

**Comment by roweryan** [comment]
The code may be valid for a single use, but multiple codes are shown - the code keeps on changing while the app is open.

**Comment by roweryan** [comment]
Example:

* All codes are hidden
* Tap the Red Hat account to get a code
* Code is unhidden and stays on screen
* Enter code on Red Hat
* Go to GitHub, tap Git Hub account to get a code
* Code is also unhidden and also stays on screen
etc.

Either only one code should be visible at a time on screen, or codes should only be displayed until they change, or the user can decide when a code gets hidden without having it pushed onto them.

**Comment by roweryan** [comment]
Could you reconsider this?

Having a password/code visible for longer than it needs to be visible is really bad!

**Comment by npmccallum** [comment]
Yes, this is a problem. I will address it.

**Comment by hpaantee** [comment]
Doesn't the app show a maximum amount of two codes per token? After that time the codes disappear and only show "- - - - - -". But it should show two codes. It happens often that when tapping, the remaining time for the first code is not long enough and you have to wait for the second. Maybe we could implement a setting? So users can choose if the app shall show one or two codes.

**Comment by roweryan** [comment]
The app shows two codes per token tap once and the code shows, but I expected tap again to hide, and didn't get any reaction so I posted here.

**Comment by xftroxgpx** [comment]
as a workaround you can tap-hold which starts the move-mode(so to speak) it but also hides the code
