### ISSUE TITLE
Allow searching

### ISSUE THREAD

**Issue by dasJ** [freeotp/freeotp-android#88]
When having a large number of OTP sites, searching manually by Icon is annyoing (especially when having multiple applications with the same Icon).
A quick ability to search (magnifying glass in the menu bar) would really help out here.

**Comment by dcousens** [comment]
Or,  an ability to filter the list by "tags"

**Comment by daviesalex** [comment]
This would be useful for employees at my firm, so we have put a $5,000 "bounty" on developing this at https://www.bountysource.com/issues/40783656-allow-searching.

**Comment by mul1sh** [comment]
@daviesalex I think this project was abandoned, so even if a developer makes a PR with the search feature, I don't think it will ever get merged and make it to the production version of the app.

But still there is an alternative fork of this project which has the search already implemented https://github.com/helloworld1/FreeOTPPlus/ plus a ton of other bug fixes.

**Comment by daviesalex** [comment]
Thanks @mul1sh. Will move this to the correct repo (actually, for us, I think the iOS might be OK and it looks like that is still maintained in freeotp-ios)

**Comment by PeterDaveHello** [comment]
Is this supported already? Didn't see the function on Android.
