### ISSUE TITLE
Allow users to change number of digits and time of OTP change

### ISSUE THREAD

**Issue by einsteinsfool** [freeotp/freeotp-android#95]
It would be cool if I could choose e.g. 10-digit codes instead of 6-digit ones.
Or change the time of OTP life from 30s to e.g. 10s.

**Comment by robbix1206** [comment]
The first one effectively can't be done.
However the second one is already in the application.

**Comment by npmccallum** [comment]
You can already do this on the server side. This needs to be done there as the server and the client must be synchronized. Thus, we cannot allow user configuration in the app. We have to use the configuration provided by the server.
