### ISSUE TITLE
Feature request: Get icon from site favicon.

### ISSUE THREAD

**Issue by peterbraden** [freeotp/freeotp-android#96]
When you add an authentication method, it would be nice if the icon defaulted to the favicon for that site, rather than being left as the default.

**Comment by mueller-ma** [comment]
I think the favicon would have way too small resolution. Use apple touch icon instead

**Comment by PanderMusubi** [comment]
Please disable this feature by default in order to incease security.

**Comment by futal** [comment]
This [StockOverflow thread](https://stackoverflow.com/questions/19029342/favicons-best-practices) lists all kinds of favicons which can be found nowadays. When you see the answers, there are a lot! The idea would be to sort them and pick the most relevant favicon.
