### ISSUE TITLE
Zero refresh time causes application to crash when a code is generated

### ISSUE THREAD

**Issue by slashrjl** [freeotp/freeotp-android#98]
If you set the refresh time to zero then generating/displaying a key will cause the whole app to crash.

(I want to be able to generate lots of HOTP codes quickly -- we use them to log into routers and I hate having to wait for the timeout to generate the next code, so I tried using zero as a time in case that allowed me to generate a new HOTP key on demand)

**Comment by joekir** [comment]
@npmccallum I didn't cherry pick from the right base for the fix ref'd above, but if you accept https://github.com/freeotp/freeotp-android/pull/113 &
https://github.com/freeotp/freeotp-android/pull/114 the diff will be more clean and I can stage a PR for this fix too :D
