### ISSUE TITLE
Tokens should be sorted alphabetically

### ISSUE THREAD

**Issue by terrycloth** [freeotp/freeotp-android#99]
Currently, tokens seem to be sorted in the reverse order that they were added. This becomes a little unwieldy, the more tokens you have. I think it would make more sense to sort the list in alphabetical order.

**Comment by metlos** [comment]
Long-tap on a token in the list and drag to re-order it...

**Comment by npmccallum** [comment]
The newest token needs to go to the top so that the user can see it immediately. Otherwise, the user might think that token addition silently failed. Afterwards, you can reorder the tokens however you like by using long-press.

**Comment by terrycloth** [comment]
FreeOTP could automatically scroll so that the new token is in view. Just a thought.

**Comment by tycho** [comment]
This is silly. There should be at least a menu option or button to sort the list alphabetically. Having to do so manually is rather painful. Long-press + drag also doesn't scroll the view when you drag to the top/bottom edge of the view.
